In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns',None)

In [ ]:
matches = pd.read_csv('matches_updated_ipl_upto_2025.csv')

In [5]:
matches.head()

,season,venue,event,winner_runs,umpire2,toss_winner,date,neutralvenue,umpire1,city,reserve_umpire,winner,eliminator,date1,method,team1,toss_decision,gender,team2,balls_per_over,winner_wickets,tv_umpire,player_of_match,match_referee,outcome,date2,match_number,matchId
0,2007/08,M Chinnaswamy Stadium,Indian Premier League,140.0,RE Koertzen,Royal Challengers Bangalore,2008-04-18,NaN,Asad Rauf,Bangalore,VN Kulkarni,Kolkata Knight Riders,NaN,NaN,NaN,Royal Challengers Bangalore,field,male,Kolkata Knight Riders,6,NaN,AM Saheba,BB McCullum,J Srinath,NaN,NaN,1.0,335982
1,2007/08,"Punjab Cricket Association Stadium, Mohali",Indian Premier League,33.0,SL Shastri,Chennai Super Kings,2008-04-19,NaN,MR Benson,Chandigarh,MSS Ranawat,Chennai Super Kings,NaN,NaN,NaN,Kings XI Punjab,bat,male,Chennai Super Kings,6,NaN,RB Tiffin,MEK Hussey,S Venkataraghavan,NaN,NaN,2.0,335983
2,2007/08,Feroz Shah Kotla,Indian Premier League,NaN,GA Pratapkumar,Rajasthan Royals,2008-04-19,NaN,Aleem Dar,Delhi,NaN,Delhi Daredevils,NaN,NaN,NaN,Delhi Daredevils,bat,male,Rajasthan Royals,6,9.0,IL Howell,MF Maharoof,GR Viswanath,NaN,NaN,3.0,335984
3,2007/08,Eden Gardens,Indian Premier League,NaN,K Hariharan,Deccan Chargers,2008-04-20,NaN,BF Bowden,Kolkata,F Gomes,Kolkata Knight Riders,NaN,NaN,NaN,Kolkata Knight Riders,bat,male,Deccan Chargers,6,5.0,Asad Rauf,DJ Hussey,FM Engineer,NaN,NaN,4.0,335986
4,2007/08,Wankhede Stadium,Indian Premier League,NaN,DJ Harper,Mumbai Indians,2008-04-20,NaN,SJ Davis,Mumbai,SN Bandekar,Royal Challengers Bangalore,NaN,NaN,NaN,Mumbai Indians,bat,male,Royal Challengers Bangalore,6,5.0,AV Jayaprakash,MV Boucher,J Srinath,NaN,NaN,5.0,335985

In [4]:
matches.columns

Index(['season', 'venue', 'event', 'winner_runs', 'umpire2', 'toss_winner',
       'date', 'neutralvenue', 'umpire1', 'city', 'reserve_umpire', 'winner',
       'eliminator', 'date1', 'method', 'team1', 'toss_decision', 'gender',
       'team2', 'balls_per_over', 'winner_wickets', 'tv_umpire',
       'player_of_match', 'match_referee', 'outcome', 'date2', 'match_number',
       'matchId'],
      dtype='object')

In [9]:
matches.drop(
    ['event','umpire2','toss_winner','neutralvenue','umpire1','reserve_umpire','match_referee','tv_umpire'],
    axis=1,
    inplace=True,
    errors='ignore'
)
matches.head()

,season,venue,winner_runs,date,city,winner,eliminator,date1,method,team1,toss_decision,gender,team2,balls_per_over,winner_wickets,player_of_match,outcome,date2,match_number,matchId
0,2007/08,M Chinnaswamy Stadium,140.0,2008-04-18,Bangalore,Kolkata Knight Riders,NaN,NaN,NaN,Royal Challengers Bangalore,field,male,Kolkata Knight Riders,6,NaN,BB McCullum,NaN,NaN,1.0,335982
1,2007/08,"Punjab Cricket Association Stadium, Mohali",33.0,2008-04-19,Chandigarh,Chennai Super Kings,NaN,NaN,NaN,Kings XI Punjab,bat,male,Chennai Super Kings,6,NaN,MEK Hussey,NaN,NaN,2.0,335983
2,2007/08,Feroz Shah Kotla,NaN,2008-04-19,Delhi,Delhi Daredevils,NaN,NaN,NaN,Delhi Daredevils,bat,male,Rajasthan Royals,6,9.0,MF Maharoof,NaN,NaN,3.0,335984
3,2007/08,Eden Gardens,NaN,2008-04-20,Kolkata,Kolkata Knight Riders,NaN,NaN,NaN,Kolkata Knight Riders,bat,male,Deccan Chargers,6,5.0,DJ Hussey,NaN,NaN,4.0,335986
4,2007/08,Wankhede Stadium,NaN,2008-04-20,Mumbai,Royal Challengers Bangalore,NaN,NaN,NaN,Mumbai Indians,bat,male,Royal Challengers Bangalore,6,5.0,MV Boucher,NaN,NaN,5.0,335985

In [12]:
matches['season'].unique()

array(['2007/08', '2009', '2009/10', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019', '2020/21', '2021', '2022',
       '2023', '2024', '2025'], dtype=object)

In [13]:
matches['season'] = matches['season'].apply(
    lambda x: int(x.split('/')[0]) if x == '2020/21'
    else int('20' + x.split('/')[1]) if '/' in x
    else int(x)
)
matches['season'].unique()

array([2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
       2019, 2020, 2021, 2022, 2023, 2024, 2025])

In [21]:
matches['winner_runs'] = matches['winner_runs'].fillna(0.0)
matches['winner_wickets'] = matches['winner_wickets'].fillna(0.0)

In [25]:
matches['winner'] = matches['winner'].fillna(matches['eliminator'])
matches['winner'].unique()

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Delhi Daredevils',
       'Royal Challengers Bangalore', 'Rajasthan Royals',
       'Kings XI Punjab', 'Deccan Chargers', 'Mumbai Indians',
       'Pune Warriors', 'Kochi Tuskers Kerala', nan,
       'Sunrisers Hyderabad', 'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Gujarat Titans', 'Lucknow Super Giants',
       'Royal Challengers Bengaluru'], dtype=object)

In [27]:
matches[matches['winner'].isna()][['matchId','winner','eliminator']]

      matchId winner eliminator
241    501265    NaN        NaN
485    829763    NaN        NaN
511    829813    NaN        NaN
744   1178424    NaN        NaN
994   1359519    NaN        NaN
1138  1473481    NaN        NaN
1149  1473492    NaN        NaN
1152  1473495    NaN        NaN

In [28]:
matches = matches[matches['winner'].notna()]
matches['winner'].isna().sum()

np.int64(0)

In [29]:
matches.head()

,season,venue,winner_runs,date,city,winner,eliminator,date1,method,team1,toss_decision,gender,team2,balls_per_over,winner_wickets,player_of_match,outcome,date2,match_number,matchId
0,2008,M Chinnaswamy Stadium,140.0,2008-04-18,Bangalore,Kolkata Knight Riders,NaN,NaN,NaN,Royal Challengers Bangalore,field,male,Kolkata Knight Riders,6,0.0,BB McCullum,NaN,NaN,1.0,335982
1,2008,"Punjab Cricket Association Stadium, Mohali",33.0,2008-04-19,Chandigarh,Chennai Super Kings,NaN,NaN,NaN,Kings XI Punjab,bat,male,Chennai Super Kings,6,0.0,MEK Hussey,NaN,NaN,2.0,335983
2,2008,Feroz Shah Kotla,0.0,2008-04-19,Delhi,Delhi Daredevils,NaN,NaN,NaN,Delhi Daredevils,bat,male,Rajasthan Royals,6,9.0,MF Maharoof,NaN,NaN,3.0,335984
3,2008,Eden Gardens,0.0,2008-04-20,Kolkata,Kolkata Knight Riders,NaN,NaN,NaN,Kolkata Knight Riders,bat,male,Deccan Chargers,6,5.0,DJ Hussey,NaN,NaN,4.0,335986
4,2008,Wankhede Stadium,0.0,2008-04-20,Mumbai,Royal Challengers Bangalore,NaN,NaN,NaN,Mumbai Indians,bat,male,Royal Challengers Bangalore,6,5.0,MV Boucher,NaN,NaN,5.0,335985

In [41]:
matches.drop(
    ['eliminator','date1','date2','toss_decision','method','gender','balls_per_over','outcome','city','match_number'],
    axis=1,
    inplace=True,
    errors='ignore'
)

In [42]:
matches.head()

,season,venue,winner_runs,date,winner,team1,team2,winner_wickets,player_of_match,matchId
0,2008,M Chinnaswamy Stadium,140.0,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders,0.0,BB McCullum,335982
1,2008,"Punjab Cricket Association Stadium, Mohali",33.0,2008-04-19,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,0.0,MEK Hussey,335983
2,2008,Feroz Shah Kotla,0.0,2008-04-19,Delhi Daredevils,Delhi Daredevils,Rajasthan Royals,9.0,MF Maharoof,335984
3,2008,Eden Gardens,0.0,2008-04-20,Kolkata Knight Riders,Kolkata Knight Riders,Deccan Chargers,5.0,DJ Hussey,335986
4,2008,Wankhede Stadium,0.0,2008-04-20,Royal Challengers Bangalore,Mumbai Indians,Royal Challengers Bangalore,5.0,MV Boucher,335985

In [46]:
print(matches.shape)
print(" -------------------- ")
print(matches.isnull().sum())
print(" -------------------- ")
print(matches.info())

(1161, 10)
 --------------------
season             0
venue              0
winner_runs        0
date               0
winner             0
team1              0
team2              0
winner_wickets     0
player_of_match    0
matchId            0
dtype: int64
 --------------------
<class 'pandas.core.frame.DataFrame'>
Index: 1161 entries, 0 to 1168
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   season           1161 non-null   int64
 1   venue            1161 non-null   object
 2   winner_runs      1161 non-null   float64
 3   date             1161 non-null   object
 4   winner           1161 non-null   object
 5   team1            1161 non-null   object
 6   team2            1161 non-null   object
 7   winner_wickets   1161 non-null   float64
 8   player_of_match  1161 non-null   object
 9   matchId          1161 non-null   int64
dtypes: float64(2), int64(2), object(6)
memory usage: 99.8+ KB
None

In [47]:
matches['date'] = pd.to_datetime(matches['date'])

In [48]:
matches.head()

,season,venue,winner_runs,date,winner,team1,team2,winner_wickets,player_of_match,matchId
0,2008,M Chinnaswamy Stadium,140.0,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders,0.0,BB McCullum,335982
1,2008,"Punjab Cricket Association Stadium, Mohali",33.0,2008-04-19,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,0.0,MEK Hussey,335983
2,2008,Feroz Shah Kotla,0.0,2008-04-19,Delhi Daredevils,Delhi Daredevils,Rajasthan Royals,9.0,MF Maharoof,335984
3,2008,Eden Gardens,0.0,2008-04-20,Kolkata Knight Riders,Kolkata Knight Riders,Deccan Chargers,5.0,DJ Hussey,335986
4,2008,Wankhede Stadium,0.0,2008-04-20,Royal Challengers Bangalore,Mumbai Indians,Royal Challengers Bangalore,5.0,MV Boucher,335985

In [49]:
matches.to_csv('cleaned_matches_till_2025.csv')